### ISSUE TITLE
safe to use on 'medium' size forum install?

### ISSUE THREAD

**Issue by anointed** [pippinsplugins/bbp-mark-as-read#8]
My forum stats approx:

28k members
screenshot:
http://www.diigo.com/item/image/39uva/o4qa

topics & replies approx 310k
screenshot:
http://www.diigo.com/item/image/39uva/patv

I'm already having a few performance issues with bbPress, but the #1 thing that every one of my moderators asked for when I first showed them bbPress was the ability to see a list of unanswered/new topics so I need to find some solution.

Given those stats, do you think it is 'safe' for me to run this plugin?

**Comment by pippinsplugins** [comment]
I responded to your bbPress.org forum post, but essentially yes. The only problem I can forsee is if a user attempts to use the "Mark all as read" feature as that will try to loop through every single forum topic.

I'd suggest disabling that feature if you decide to use this.

**Comment by anointed** [comment]
wasn't sure if you would check here or on bbPress and after I posted it over there, it dawned on me that its probably more appropriate to ask here.

I'll read through the code and find the filter to remove the button.

I'm so glad to hear that it should work properly, but then again, I should have known better anyhow as you built it :)

**Comment by pippinsplugins** [comment]
Ha, if you looked at some of my old code (some of it still in the wild) that would not always be a safe assumption ;)

**Comment by anointed** [comment]
well i can safely say without a doubt that I now trust your code more than just about anyone out there. Don't sell yourself short, your an animal
